# Site settings
title: Lode King
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  In order to keep our brand consistent across many mediums, we've developed these guidelines. Please take some time to familiarize yourself with them.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brand.lodeking.com" # the base hostname & protocol for your site
exclude: ['/node_modules/','**.sublime-project','**.sublime-workspace','gulpfile.js','package.json','.git']

# Build settings
markdown: kramdown
